---
- hosts: all
  become: yes

  tasks:
    - name: enable linger on ec2-user
      command: "loginctl enable-linger ec2-user"

    - name: update current packages
      dnf:
        name: "*"
        state: latest
    
    - name: install firewall related package
      dnf:
        name:
          - firewalld
          - python-firewall
        state: latest

    - name: install podman
      dnf:
        name: podman
        state: latest

    - name: enable port for mariadb
      ansible.posix.firewalld:
        port: 3310/tcp
        permanent: true
        state: enabled
